// Generated by CoffeeScript 1.8.0
(function() {
  var fs;

  fs = require('fs');

  fs.readFile('names-male.txt', 'utf8', function(err, data) {
    if (err != null) {
      return console.log(err);
    }
    return console.log(data);
  });

}).call(this);

//# sourceMappingURL=index.js.map
